/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.sql.*;
import dal.ModuloConexao;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Edson Macaule
 */
public class TelaFuncionario extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    private String sexo;
    private String estado;
    private String filhos;

    /**
     * Creates new form TelaFuncionario
     */
    public TelaFuncionario() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    private void adicionar() {
        String sql = "insert into tbfucionarios (nome,nascimento,nascionalidade,sexo,documento,numero,estado,filhos,numfilhos,endereco,bairro,quarteirao,casa,contacto,nivel,cargo,salario) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtNome.getText());
            pst.setString(2, txtNasc.getText());
            pst.setString(3, txtNacion.getText());
            pst.setString(4, sexo);
            pst.setString(5, cbTipoDoc.getSelectedItem().toString());
            pst.setString(6, txtNumDoc.getText());
            pst.setString(7, estado);
            pst.setString(8, filhos);
            pst.setString(9, txtNumFilhos.getText());
            pst.setString(10, txtEnderc.getText());
            pst.setString(11, txtBairro.getText());
            pst.setString(12, txtQuarteirao.getText());
            pst.setString(13, txtCasa.getText());
            pst.setString(14, txtCell.getText());
            pst.setString(15, cbAcademico.getSelectedItem().toString());
            pst.setString(16, cbCargo.getSelectedItem().toString());
            pst.setString(17, txtSal.getText().replace(",", "."));
            
            if (rbMasc.isSelected()) {
                sexo = rbMasc.getText();

            } else {
                sexo = rbFem.getText();
            }
            
            if (rbSolteiro.isSelected()) {
                estado = rbSolteiro.getText();

            } else {
                estado = rbCasado.getText();

                if (rbViuvo.isSelected()) {
                    estado = rbViuvo.getText();

                } else {
                    estado = rbDivorciado.getText();
                }

                
                if (rbSim.isSelected()) {
                    filhos = rbSim.getText();

                } else {
                    filhos = rbNao.getText();
                }
                
              if ((txtNome.getText().isEmpty() || (txtNasc.getText().isEmpty()||(txtNacion.getText().isEmpty()||(txtNumDoc.getText().isEmpty()||(txtEnderc.getText().isEmpty()||(txtBairro.getText().isEmpty()||(txtQuarteirao.getText().isEmpty()||(txtCasa.getText().isEmpty()||(txtCell.getText().isEmpty()||(txtSal.getText().isEmpty()))))))))))) {
                JOptionPane.showMessageDialog(null, "preencha todos os campos obrigatórios");

                int adicionado = pst.executeUpdate();
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Funcionário cadastrado com sucesso");
                    txtNome.setText(null);
                    txtNasc.setText(null);
                   txtNacion.setText(null);
                   txtNumDoc.setText(null);
                   txtEnderc.setText(null);
                  txtBairro.setText(null);
                   txtQuarteirao.setText(null);
                   txtCasa.setText(null);
                   txtCell.setText(null);
                   txtSal.setText(null);
                }
          }
          }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        bgCivil = new javax.swing.ButtonGroup();
        bgFilhos = new javax.swing.ButtonGroup();
        lbIdFunc = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbNasc = new javax.swing.JLabel();
        lbNascion = new javax.swing.JLabel();
        lbTipoDoc = new javax.swing.JLabel();
        cbTipoDoc = new javax.swing.JComboBox();
        lbNumDOc = new javax.swing.JLabel();
        txtNumDoc = new javax.swing.JTextField();
        lbSexo = new javax.swing.JLabel();
        rbFem = new javax.swing.JRadioButton();
        rbMasc = new javax.swing.JRadioButton();
        lbEnder = new javax.swing.JLabel();
        txtEnderc = new javax.swing.JTextField();
        lbContac = new javax.swing.JLabel();
        txtCell = new javax.swing.JTextField();
        txtIdFunc = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtNasc = new javax.swing.JTextField();
        txtNacion = new javax.swing.JTextField();
        lbAcadem = new javax.swing.JLabel();
        cbAcademico = new javax.swing.JComboBox();
        lbCargo = new javax.swing.JLabel();
        lbCivil = new javax.swing.JLabel();
        rbSolteiro = new javax.swing.JRadioButton();
        rbCasado = new javax.swing.JRadioButton();
        rbViuvo = new javax.swing.JRadioButton();
        rbDivorciado = new javax.swing.JRadioButton();
        lbFilhos = new javax.swing.JLabel();
        rbSim = new javax.swing.JRadioButton();
        rbNao = new javax.swing.JRadioButton();
        lbNumFilhos = new javax.swing.JLabel();
        txtNumFilhos = new javax.swing.JTextField();
        cbCargo = new javax.swing.JComboBox();
        lbSal = new javax.swing.JLabel();
        txtSal = new javax.swing.JTextField();
        btAdicionar = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        lbTexto = new javax.swing.JLabel();
        lbBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lbQuarteirao = new javax.swing.JLabel();
        txtQuarteirao = new javax.swing.JTextField();
        lbCasa = new javax.swing.JLabel();
        txtCasa = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Funcionários");
        setPreferredSize(new java.awt.Dimension(728, 608));

        lbIdFunc.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbIdFunc.setText("*Id_Funcioanário:");

        lbNome.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbNome.setText("*Nome:");

        lbNasc.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbNasc.setText("*Nascimento:");

        lbNascion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbNascion.setText("*Nascionalidade:");

        lbTipoDoc.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbTipoDoc.setText("Tipo_Documento:");

        cbTipoDoc.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbTipoDoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "B.I", "Passaporte", "Carta de Condução", "Cartão de Eleitor", "Dire" }));

        lbNumDOc.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbNumDOc.setText("*Nº_Doc:");

        lbSexo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbSexo.setText("Sexo:");

        bgSexo.add(rbFem);
        rbFem.setSelected(true);
        rbFem.setText("Feminino");

        bgSexo.add(rbMasc);
        rbMasc.setText("Masculino");

        lbEnder.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbEnder.setText("*Endereço:");

        lbContac.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbContac.setText("*Contacto:");

        txtIdFunc.setEditable(false);
        txtIdFunc.setEnabled(false);

        lbAcadem.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbAcadem.setText("Nivel Academico:");

        cbAcademico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbAcademico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5ª Classe", "7ª Classe", "10ª Classe", "12ª Classe", "Técnico Medio Profissional", "Técnico Superior", "Lincenciado", "Mestre", "Doutorado", " " }));

        lbCargo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbCargo.setText("Cargo:");

        lbCivil.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbCivil.setText("Estado Civil:");

        bgCivil.add(rbSolteiro);
        rbSolteiro.setSelected(true);
        rbSolteiro.setText("Solteiro");

        bgCivil.add(rbCasado);
        rbCasado.setText("Casado");

        bgCivil.add(rbViuvo);
        rbViuvo.setText("Viúvo");

        bgCivil.add(rbDivorciado);
        rbDivorciado.setText("Divorciado");

        lbFilhos.setText(" Têm Filhos?:");

        bgFilhos.add(rbSim);
        rbSim.setText("Sim");

        bgFilhos.add(rbNao);
        rbNao.setSelected(true);
        rbNao.setText("Não");

        lbNumFilhos.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbNumFilhos.setText("Quantos:");

        cbCargo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Guarda", "Zeladora(o)", "Administrativo", "Secretário(a)" }));

        lbSal.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbSal.setText("*Salário:");

        btAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adicionar.png"))); // NOI18N
        btAdicionar.setToolTipText("Adicionar");
        btAdicionar.setPreferredSize(new java.awt.Dimension(80, 80));
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        btPesquisar.setToolTipText("Pesquisar");
        btPesquisar.setPreferredSize(new java.awt.Dimension(80, 80));

        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N
        btEditar.setToolTipText("Editar");
        btEditar.setPreferredSize(new java.awt.Dimension(80, 80));

        btRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Apagar.png"))); // NOI18N
        btRemover.setToolTipText("Remover");
        btRemover.setPreferredSize(new java.awt.Dimension(80, 80));

        lbTexto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbTexto.setText("*Campos Obrigatórios");

        lbBairro.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbBairro.setText("*Bairro:");

        lbQuarteirao.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbQuarteirao.setText("*Quarteirão:");

        lbCasa.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbCasa.setText("*Casa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbEnder)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtEnderc, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lbBairro))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbQuarteirao)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtQuarteirao, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbCasa)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lbContac)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCell)
                                            .addComponent(txtBairro)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbCivil)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbSolteiro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbCasado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbViuvo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbDivorciado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbFilhos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbSim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbNao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbNumFilhos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumFilhos))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbSexo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbFem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbMasc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbTipoDoc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbNumDOc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumDoc)))
                                .addGap(13, 13, 13))
                            .addComponent(lbTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbIdFunc)
                                    .addComponent(lbNome)
                                    .addComponent(lbNasc))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtIdFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 452, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbNascion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNacion, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtNome))))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbAcadem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbCargo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbSal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSal, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdFunc)
                    .addComponent(txtIdFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNasc)
                    .addComponent(txtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNascion)
                    .addComponent(txtNacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipoDoc)
                    .addComponent(cbTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbFem)
                    .addComponent(rbMasc)
                    .addComponent(lbSexo)
                    .addComponent(lbNumDOc)
                    .addComponent(txtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCivil)
                    .addComponent(rbSolteiro)
                    .addComponent(rbCasado)
                    .addComponent(rbViuvo)
                    .addComponent(rbDivorciado)
                    .addComponent(lbFilhos)
                    .addComponent(rbSim)
                    .addComponent(rbNao)
                    .addComponent(lbNumFilhos)
                    .addComponent(txtNumFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEnder)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEnderc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbBairro)
                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuarteirao)
                    .addComponent(txtQuarteirao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCasa)
                    .addComponent(txtCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbContac)
                    .addComponent(txtCell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAcadem)
                    .addComponent(cbAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCargo)
                    .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSal)
                    .addComponent(txtSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        setBounds(0, 0, 728, 608);
    }// </editor-fold>//GEN-END:initComponents

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        adicionar();
    }//GEN-LAST:event_btAdicionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCivil;
    private javax.swing.ButtonGroup bgFilhos;
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btRemover;
    private javax.swing.JComboBox cbAcademico;
    private javax.swing.JComboBox cbCargo;
    private javax.swing.JComboBox cbTipoDoc;
    private javax.swing.JLabel lbAcadem;
    private javax.swing.JLabel lbBairro;
    private javax.swing.JLabel lbCargo;
    private javax.swing.JLabel lbCasa;
    private javax.swing.JLabel lbCivil;
    private javax.swing.JLabel lbContac;
    private javax.swing.JLabel lbEnder;
    private javax.swing.JLabel lbFilhos;
    private javax.swing.JLabel lbIdFunc;
    private javax.swing.JLabel lbNasc;
    private javax.swing.JLabel lbNascion;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNumDOc;
    private javax.swing.JLabel lbNumFilhos;
    private javax.swing.JLabel lbQuarteirao;
    private javax.swing.JLabel lbSal;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JLabel lbTexto;
    private javax.swing.JLabel lbTipoDoc;
    private javax.swing.JRadioButton rbCasado;
    private javax.swing.JRadioButton rbDivorciado;
    private javax.swing.JRadioButton rbFem;
    private javax.swing.JRadioButton rbMasc;
    private javax.swing.JRadioButton rbNao;
    private javax.swing.JRadioButton rbSim;
    private javax.swing.JRadioButton rbSolteiro;
    private javax.swing.JRadioButton rbViuvo;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCasa;
    private javax.swing.JTextField txtCell;
    private javax.swing.JTextField txtEnderc;
    private javax.swing.JTextField txtIdFunc;
    private javax.swing.JTextField txtNacion;
    private javax.swing.JTextField txtNasc;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumDoc;
    private javax.swing.JTextField txtNumFilhos;
    private javax.swing.JTextField txtQuarteirao;
    private javax.swing.JTextField txtSal;
    // End of variables declaration//GEN-END:variables

    
}
